### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wilkgr76** [wilkgr76/eggwars#1]
- [ ] Win checking
- [ ] Arena reset
- [ ] Stick spawner (will use wooden block texture)
- [ ] Add Sokomine/mobf_traders or other traders mod & modify
- [ ] Set time_speed to 0?

**Comment by Panquesito7** [comment]
> * Kill player who falls off

Maybe an easier way to do this is to add a block that makes 100 damage. 🙂
I'll perhaps create a pull request to fix this (without adding new blocks).
